# Generated by Django 2.0.7 on 2018-07-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.TextField(blank=True, null=True)),
                ('number_633', models.FloatField(blank=True, db_column='633', null=True)),
            ],
            options={
                'db_table': 'user_dp',
                'managed': False,
            },
        ),
    ]
