# Generated by Django 2.0.7 on 2018-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('dataset', models.IntegerField(blank=True, null=True)),
                ('package', models.IntegerField(blank=True, null=True)),
                ('algorithm', models.IntegerField(blank=True, null=True)),
                ('nvertices', models.IntegerField(blank=True, null=True)),
                ('nedges', models.IntegerField(blank=True, null=True)),
                ('nthreads', models.IntegerField(blank=True, null=True)),
                ('nodes_in_largest_wcc', models.FloatField(blank=True, db_column='Nodes.in.largest.WCC', null=True)),
                ('edges_in_largest_wcc', models.FloatField(blank=True, db_column='Edges.in.largest.WCC', null=True)),
                ('nodes_in_largest_scc', models.FloatField(blank=True, db_column='Nodes.in.largest.SCC', null=True)),
                ('edges_in_largest_scc', models.FloatField(blank=True, db_column='Edges.in.largest.SCC', null=True)),
                ('average_clustering_coefficient', models.FloatField(blank=True, db_column='Average.clustering.coefficient', null=True)),
                ('number_of_triangles', models.FloatField(blank=True, db_column='Number.of.triangles', null=True)),
                ('fraction_of_closed_triangles', models.FloatField(blank=True, db_column='Fraction.of.closed.triangles', null=True)),
                ('diameter_longest_shortest_path_field', models.FloatField(blank=True, db_column='Diameter..longest.shortest.path.', null=True)),
                ('x90_percentile_effective_diameter', models.FloatField(blank=True, db_column='X90.percentile.effective.diameter', null=True)),
                ('runtime', models.FloatField(blank=True, null=True)),
                ('classif', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'learning_set',
                'managed': False,
            },
        ),
    ]
