# Generated by Django 2.0.7 on 2018-08-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0003_learningset1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.TextField(default=' ')),
            ],
            options={
                'db_table': 'input-info',
                'managed': False,
            },
        ),
    ]
