# Generated by Django 2.0.7 on 2018-08-09 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_input'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={},
        ),
    ]
