# Generated by Django 2.0.7 on 2018-08-09 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_auto_20180809_0042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='input',
            options={'managed': False},
        ),
    ]
